name: Setup Registry

inputs:
  token:
    description: 'GitHub token for registry access' 
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Setup registry string
      shell: bash
      run: |
        REGISTRY_USER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        echo "REGISTRY_USER=$REGISTRY_USER" >> $GITHUB_ENV
        echo "IMAGE_PREFIX=${{ env.REGISTRY }}/$REGISTRY_USER/${{ env.PROJECT_NAME }}" >> $GITHUB_ENV

    - name: Registry login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ inputs.token }} 

