App\Entity\Album:
  attributes:
    id:
      groups:
        - 'album:read'
        - 'album:collection:read'
        - 'music:read'
        - 'dashboard:read'
        - 'playlist:read'
    title:
      groups:
        - 'album:read'
        - 'album:collection:read'
        - 'album:write'
        - 'album:update'
        - 'music:read'
        - 'playlist:read'
        - 'playlist:collection:read'
        - 'dashboard:read'
    releaseDate:
      groups:
        - 'album:read'
        - 'album:write'
        - 'album:update'
    musics:
      groups:
        - 'album:read'
        - 'album:write'
        - 'album:update'

App\Entity\AlbumMusic:
  attributes:
    album:
      groups:
        - 'music:read'
    music:
      groups:
        - 'album:read'
        - 'album:write'
        - 'album:update'
    position:
      groups:
        - 'album:read'
        - 'album:write'
        - 'album:update'
    addedAt:
      groups:
        - 'album:read'
