App\Entity\Album:
  attributes:
    id:
      groups:
        - 'album:read'
        - 'album:collection:read'
        - 'music:read'
        - 'dashboard:read'
        - 'playlist:read'
        - 'artist:read'
    title:
      groups:
        - 'album:read'
        - 'album:collection:read'
        - 'album:write'
        - 'album:update'
        - 'music:read'
        - 'playlist:read'
        - 'playlist:collection:read'
        - 'dashboard:read'
        - 'artist:read'
    artist:
      groups:
        - 'album:read'
        - 'album:collection:read'
        - 'playlist:read'
        - 'dashboard:read'
    releaseDate:
      groups:
        - 'album:read'
        - 'album:write'
        - 'album:update'
        - 'artist:read'
    coverName:
      groups:
        - 'album:read'
        - 'artist:read'
    cover:
      groups:
        - 'album:write'
    wallpaperName:
      groups:
        - 'album:read'
    wallpaper:
      groups:
        - 'album:write'
    musics:
      groups:
        - 'album:read'
        - 'album:write'
        - 'album:update'

App\Entity\AlbumMusic:
  attributes:
    album:
      groups:
        - 'playlist:read'
        - 'music:read'
    music:
      groups:
        - 'album:read'
        - 'album:write'
        - 'album:update'
    position:
      groups:
        - 'album:read'
        - 'album:write'
        - 'album:update'
    addedAt:
      groups:
        - 'album:read'
