App\Entity\Album:
  attributes:
    id:
      groups:
        - 'album:read'
        - 'album:collection:read'
        - 'music:read'
        - 'dashboard:read'
        - 'playlist:read'
    title:
      groups:
        - 'album:read'
        - 'album:collection:read'
        - 'album:write'
        - 'album:update'
        - 'music:read'
        - 'playlist:read'
        - 'playlist:collection:read'
        - 'dashboard:read'
    releaseDate:
      groups:
        - 'album:read'
        - 'album:write'
        - 'album:update'
    musics:
      groups:
        - 'album:read'
        - 'album:write'
        - 'album:update'

