App\Entity\Category:
  attributes:
    id:
      groups:
        - 'album:read'
        - 'album:collection:read'
        - 'music:read'
        - 'dashboard:read'
    name:
      groups:
        - 'album:read'
        - 'album:collection:read'
        - 'music:read'
        - 'dashboard:read'

