App\Entity\Category:
  attributes:
    id:
      groups:
        - 'music:read'
        - 'dashboard:read'
        - 'artist:read'
    name:
      groups:
        - 'music:read'
        - 'dashboard:read'
        - 'artist:read'

