App\Entity\LastListened:
  attributes:
    target:
      groups:
        - "dashboard:read"
        - "last_listened:collection:read"
    listenedAt:
      groups:
        - "dashboard:read"
        - "last_listened:collection:read"
