App\Entity\LastListened:
  attributes:
    target:
      groups:
        - 'dashboard:read'
        - 'last_listend:collection:read'
    listenedAt:
      groups:
        - 'dashboard:read'
        - 'last_listend:collection:read'

