App\Entity\QueueBase:
  attributes:
    queueItems:
      groups:
        - 'queue:read'

App\Entity\QueueItem:
  attributes:
    music:
      groups:
        - 'queue:read'
    position:
      groups:
        - 'queue:read'


