services:
  php:
    build:
      dockerfile: ./.devops/php/Dockerfile
    volumes:
      - ./api:/srv
      - /srv/vendor
      - /srv/var
    networks:
      - beatly

  web:
    depends_on:
      - php
    build:
      dockerfile: ./.devops/nginx/Dockerfile
    volumes:
      - ./api/public:/srv/public
    networks:
      - beatly

  front:
    build:
      dockerfile: ./.devops/node/Dockerfile
      target: dev
    volumes:
      - ./front:/app
      - /app/node_modules 
    networks:
      - beatly

  db:
    image: mariadb:10.3.0
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - beatly

  embedder:
    build:
      dockerfile: ./.devops/python/Dockerfile
    volumes:
      - ./embedder:/app
    networks:
      - beatly

  qdrant:
    image: qdrant/qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - beatly

volumes:
  db_data:
  qdrant_data:

networks:
  beatly:
