services:
  php:
    image: ${REGISTRY}-php:latest
    build:
      dockerfile: ./.devops/php/Dockerfile
    volumes:
      - ./api:/srv
      - ./api/vendor:/srv/vendor
      - ./api/var:/srv/var
    networks:
      - beatly

  web:
    depends_on:
      - php
    image: ${REGISTRY}-web:latest
    build:
      dockerfile: ./.devops/nginx/Dockerfile
    volumes:
      - ./api/public:/srv/public
    networks:
      - beatly

  front:
    image: ${REGISTRY}-front:latest
    build:
      dockerfile: ./.devops/node/Dockerfile
      target: prod
    volumes:
      - ./front:/app
      - /app/node_modules 
    networks:
      - beatly

  db:
    image: mariadb:10.3.0
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - beatly

volumes:
  db_data:

networks:
  beatly:

