services:
  php:
    image: ${REGISTRY}-php:latest
    build:
      dockerfile: ./.devops/php/Dockerfile
    volumes:
      - ./api:/srv
      - vendor:./api/vendor
      - var:./api/var
    networks:
      - beatly

  web:
    depends_on:
      - php
    image: ${REGISTRY}-web:latest
    build:
      dockerfile: ./.devops/nginx/Dockerfile
    volumes:
      - ./api/public:/srv/public
    networks:
      - beatly

  front:
    image: ${REGISTRY}-front:latest
    build:
      dockerfile: ./.devops/node/Dockerfile
      target: prod
    volumes:
      - ./front:/app
      - node_modules:./front/node_modules
    networks:
      - beatly

  db:
    image: mariadb:10.3.0
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - beatly

  embedder:
    image: ${REGISTRY}-embedder:latest
    build:
      dockerfile: ./.devops/python/Dockerfile
    volumes:
      - ./embedder:/app
    networks:
      - beatly

  qdrant:
    image: qdrant/qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - beatly

  ollama:
    image: ${REGISTRY}-ollama:latest
    build:
      dockerfile: ./.devops/ollama/Dockerfile
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - beatly

  mailbox:
    image: mailhog/mailhog
    networks:
      - beatly

volumes:
  vendor:
  var:
  node_modules:
  db_data:
  qdrant_data:
  ollama_data:

networks:
  beatly:

