vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    music_file:
      uri_prefix: /uploads/musics
      upload_destination: '%kernel.project_dir%%env(string:PRIVATE_UPLOADS_PATH)%/musics'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    music_cover:
      uri_prefix: /uploads/musics/covers
      upload_destination: '%kernel.project_dir%%env(string:SSR_PUBLIC_UPLOADS_PATH)%/musics/covers'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

