vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    music_file:
      uri_prefix: /uploads/musics
      upload_destination: '%kernel.project_dir%%env(PRIVATE_UPLOADS_PATH)%/musics'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

