# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $publicUploadsPath: '%env(string:PUBLIC_UPLOADS_PATH)%'
            string $privateUploadsPath: '%env(string:PRIVATE_UPLOADS_PATH)%'
            string $ssrPublicUploadsPath: '%env(string:SSR_PUBLIC_UPLOADS_PATH)%'
            string $frontResetUrl: '%env(string:FRONT_RESET_URL)%'
            string $frontLoginUrl: '%env(string:FRONT_LOGIN_URL)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/DataFixtures/Sample/'
            - '../src/Kernel.php'

    App\Service\Client\EmbedderClient:
        arguments:
            $baseUrl: '%env(string:EMBEDDER_URL)%'
    
    App\Service\Client\QdrantClient:
        arguments:
            $baseUrl: '%env(string:QDRANT_URL)%'

    App\Service\Client\OllamaClient:
        arguments:
            $baseUrl: '%env(string:OLLAMA_URL)%'

    App\Service\Prompt\PromptBuilder:
        arguments:
            $basePath: '%kernel.project_dir%/prompt'

when@dev:
    services:
        App\DataFixtures\Sample\SampleLoader: ~
