name: Ollama docker image

on:
  push:
    branches:
      - feat/ci
    paths:
      - '.devops/ollama/**'

env:
  REGISTRY: ghcr.io
  PROJECT_NAME: beatly

jobs:
  build-push-ollama-image:
    name: Build and push ollama image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Registry
        uses: ./.github/workflows/callables/registry
        with:
          token: ${{ secrets.IMAGE_TOKEN }}

      - name: Build / Push ollama image
        uses: ./.github/workflows/callables/build-push
        with:
          dockerfile: ./.devops/ollama/Dockerfile
          image: ollama

  deploy-ollama-image:
    name: Deploy ollama image
    runs-on: ubuntu-latest
    needs: build-push-ollama-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy image
        uses: ./.github/workflows/callables/deployment
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.PROD_HOST }}
          user: ${{ secrets.PROD_USER }}
          path: ${{ secrets.PROD_PATH }}
          images: ollama
